simple_photos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from posts.views import PostFeed, CreatePost, CreateComment, CreateLike, \
        UploadImage
from account_profile.views import ProfileView, ProfileEdit, ProfileSignupView,\
        UserList, DeleteUser, SendInvitation, RequestInvitation

urlpatterns = [
    path('', PostFeed.as_view(), name='index'),
    path('add/', CreatePost.as_view(), name='add'),
    path('add/image/', UploadImage.as_view(), name='add-image'),
    path('admin/', admin.site.urls),
    path(
        'login/',
        LoginView.as_view(
            template_name="account/login.html",
        ),
        name="account_login"
    ),
    path('logout/', LogoutView.as_view(), name="account_logout"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEdit.as_view(), name='profile'),
    path('comment/', CreateComment.as_view(), name='comment'),
    path('like/', CreateLike.as_view(), name='like'),
    path('create/<str:token>/', ProfileSignupView.as_view(), name='account_signup'),
    path('users/', UserList.as_view(), name="account_users"),
    path('users/delete/', DeleteUser.as_view(), name="account_users_delete"),
    path('users/invite/', SendInvitation.as_view(), name="account_users_invite"),
    path('users/invite-request/', RequestInvitation.as_view(), name="account_invite_sent"),

    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.core.files.storage import default_storage

from PIL import Image
import io

from account_profile.models import Profile


class Post(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    description = models.TextField()
    link = models.CharField(max_length=300)
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def liked_by(self):
        profiles = []
        for like in self.like_set.all():
            profiles.append(like.profile)
        return profiles 

    def __str__(self):
        return "{} - {}".format(self.profile.display_name, self.description[:30])


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images", blank=True, null=True)
    image = models.ImageField(upload_to="posts/", blank=True)

    def save(self, *args, **kwargs):
        super(PostImage, self).save(*args, **kwargs)
        image = Image.open(self.image)
        width, height = image.size

        if width > 1100 or height > 1100:
            if width > height:
                factor = 1100 / width 
            else:
                factor = 1100 / height 

        size = ( int(width * factor), int(height * factor))
        image = image.resize(size, Image.ANTIALIAS)

        in_mem_file = io.BytesIO()
        image.save(in_mem_file, format="JPEG")

        with default_storage.open(self.image.name, 'w') as f:
            f.write(in_mem_file.getvalue())



class Comment(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)


class Like(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
      html, body {
        overflow-x: hidden;
        background-color: #F4F4F4;
      }
    </style>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head-css %}
      
     <style>
      .post {
        margin-top: 10px;
      }

      .carousel-image {
        position: fixed;
        left: 50%;
        transform: translateX(-50%);
        max-width: 100%; 
        max-height: 85%;
        margin-top: -30px;
      }
      
      .carousel-control-next {
        position: fixed;
      }
      .carousel-control-prev {
        position: fixed;
      }

      .profile-pic {
        width: 65px;
        height: 65px;
        position: relative;
        overflow: hidden;
        border-radius: 50%;
        object-fit: cover;
        padding: 10px;
      }
      .upload-preview {
        position: relative;
        overflow: hidden;
        object-fit: contain;
      }

      .image-display {
          display: block;
          margin-left: auto;
          margin-right: auto;
          max-height: 600px;
          max-width: 100%;
          width: 100%;
          object-fit: cover;
       }

        .crop img {
            object-fit: cover;
            height: 110px;
            width: 110px;
        }
        /* The Modal (background) */
        .modal {
          display: none; /* Hidden by default */
          position: fixed; /* Stay in place */
          z-index: 1; /* Sit on top */
          padding-top: 100px; /* Location of the box */
          left: 0;
          top: 0;
          width: 100%; /* Full width */
          height: 100%; /* Full height */
          overflow: hidden; /* Enable scroll if needed */
          background-color: rgb(0,0,0); /* Fallback color */
          background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
        }


        /* Modal Content (Image) */
        .modal-content {
          display: block;
          margin: auto;
          width: auto;
          height: auto;
          max-width: 85%;
          max-height: 85%;
        }

        /* Caption of Modal Image (Image Text) - Same Width as the Image */
        #caption {
          margin: auto;
          display: block;
          width: 80%;
          max-width: 700px;
          text-align: center;
          color: #ccc;
          padding: 10px 0;
          height: 150px;
        }

        /* Add Animation - Zoom in the Modal */
        .modal-content, #caption {
          animation-name: zoom;
          animation-duration: 0.4s;
        }

        @keyframes zoom {
          from {transform:scale(0)}
          to {transform:scale(1)}
        }

        /* The Close Button */
        .close {
          position: absolute;
          top: 15px;
          right: 35px;
          color: #f1f1f1;
          font-size: 40px;
          font-weight: bold;
          transition: 0.3s;
        }

        .close:hover,
        .close:focus {
          color: #bbb;
          text-decoration: none;
          cursor: pointer;
        }

     </style>
    {% endblock %}

    {% block head-js %}
    {% endblock %}

    <title>{% block title %}Simple Photos{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light" style="background-color: white; max-height: 50px;">
      <a class="navbar-brand" href="/"><img height="30" src="" alt="Simple Photos"/></a>
      <button class="navbar-toggler" style="z-index: 1" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" style="z-index: 10; background-color: white;">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/profile">Profile</a>
          </li>
          {% if request.user.is_staff %}
          <li class="nav-item active">
            <a class="nav-link" href="/users">Users</a>
          </li>
          {% endif %}
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="btn btn-outline-success btn-sm" style="margin-top: 4px;" href="/add"><i class="fa fa-plus" aria-hidden="true"></i> New Post</a>
          </li>
          {% endif %}
          {% if request.user.is_staff %}
          <li class="nav-item" style="padding-left: 5px;">
            <a class="btn btn-outline-info btn-sm" style="margin-top: 4px;" href="#"><i class="fa fa-plus" aria-hidden="true"></i> Invite</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item" style="margin-right: 10px;">
              <a href="/logout/" class="btn btn-outline-success btn-sm">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item" style="margin-right: 10px;">
              <a href="/login/" class="btn btn-outline-success btn-sm">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <br>
    {% block content %}
    {% endblock %}
    <footer class="text-muted" style="margin-top: 120px;">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <center><p>Simple Photos is a Open Source project licensed under GNU GPLv3.</p></center>
        </div>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block end-js %}
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
    <div class="row" id="vue-app">
      {% for post in posts %}
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
            <div class="post" style="border: 1px solid #D2D2D2; border-radius: 8px; background-color: white;">
              {#{% include "includes/profile-display.html" %}#}
              <div class="row">
                <div class="col-md-12">
                    {% include "includes/carousel.html" with images=post.images.all %}
                </div>
              </div>
              {#{% include "includes/profile-display.html" %}#}
              <div class="row">
                <div class="col-md-8">
                  <div class="" style="display: inline; float: left; padding-left: 10px;">
                    <p style="display: inline; color: blue;"><b>{{ post.profile.display_name }}</b></p>
                    <p style="display: inline;"> - {{ post.date }}</p>
                  </div>
                </div>
              </div>
              {% if post.images.all.count > 1 %}
              <br>
              {% endif %}
              <div class="row">
                <div class="col-md-12 ">
                  <p style="margin-left: 20px; margin-right: 20px;">{{ post.description }}</p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 ">

                  <button v-on:click="comment_show" data-form="comment-{{ post.pk }}" id="comment-button-{{ post.pk }}" style="margin: 3px; margin-right: 10px; float: right;" class="btn btn-outline-info btn-sm "><i class="fa fa-comment" aria-hidden="true"></i> Comment</button>
                  <form method="POST" action="/like/">
                    {% csrf_token %}
                    <input type="hidden" name="post" value="{{ post.pk }}"/>
                    {% if profile in post.liked_by %}
                      <input type="hidden" name="liked" value="false"/>
                      <button v-on:click="like_post" id="like-button-{{ post.pk }}" style="margin: 3px; float: right;" class="btn btn-outline-danger btn-sm "><i class="fa fa-heart"></i> Liked</button>
                    {% else %}
                      <input type="hidden" name="liked" value="true"/>
                      <button v-on:click="like_post" id="like-button-{{ post.pk }}" style="margin: 3px; float: right;" class="btn btn-outline-danger btn-sm "><i class="fa fa-heart-o"></i></button>
                    {% endif %}
                  </form>
                  <div class="likes d-inline-block" style="margin-top: 5px; padding-left: 10px;">
                  {% for person in post.liked_by %}
                    {% if forloop.first %}
                      <p class="d-inline">Liked by:</p>
                    {% endif %}
                    <p class="d-inline" style="color: #3333EE;">{{ person.display_name }}</p>{% if not forloop.last %},{% endif %}
                  {% endfor %}
                  </div>
                </div>
              </div>
              {% if post.comment_set.all %}
              <hr style="margin: 5px;">
              {% endif %}
              <div id="comment-{{ post.pk }}" style="display: none;">
                <br>
                <div class="row justify-content-center">
                  <div class="col-md-10">
                    {% if profile.image %}
                      <img class="d-inline-block profile-pic" src="{{ profile.image.url }}" />
                    {% else %}
                      <img class="d-inline-block profile-pic" src="https://api.adorable.io/avatars/130/{{ profile.user.pk }}@adorable.io.png" />
                    {% endif %}
                    <p class="d-inline-block" style="position: relative; left: 0px; top: -20px; color: blue;"><b>{{ profile.display_name }}:</b></p>
                    <form method="POST" action="/comment/" style="margin-left: 70px; margin-top: -30px; margin-right: 5px;">
                      {% csrf_token %}
                      <textarea class="textarea form-control" style="width: 100%;" name="text"></textarea>
                      <input type="hidden" name="post" value="{{ post.pk }}"/>
                      <input style="margin: 3px;" class="btn btn-outline-success btn-sm" type="submit" value="Submit"/>
                    </form>
                    <br>
                  </div>
                </div>
              </div>
              <div class="post-comment" style="margin-top: 3px; margin-left: 15px; {% if post.comment_set.all %}margin-bottom: -30px;{% endif %}">
                {% for comment in post.comment_set.all %}
                  {% include "includes/comment.html" with comment=comment %}
                {% endfor %}
              </div>
            </div>
        </div>
      {% endfor %}
      </div>
    </div>
  <br>
</div>
{% endblock %}

{% block end-js %}
<script>
  var app = new Vue({
    el: '#vue-app',
    data: {
    },
    methods: {
      comment_show: function(event) {
        var form = $("#" + $(event.srcElement).attr("data-form"));
        form.toggle();
      },
      like_post: function (event) {
        event.preventDefault();
        var form = $(event.srcElement.closest("form"));
        console.log(form);
        axios({
          method: 'post',
          url: '/like/',
          data: form.serialize(),
        })
        .then(function (response) {
            //handle success
            var liked = $($(event.srcElement.closest("form")).find("input[name=liked]")[0]);
            var button = $(event.srcElement.closest("button"));
            console.log(liked);
            if (response.data.liked == "true") {
              liked.val("false");
              button.html("<i class='fa fa-heart'></i> Liked");
            } else {
              liked.val("true");
              button.html("<i class='fa fa-heart-o'></i>");
            };
        })
        .catch(function (response) {
            //handle error
            console.log(response);
        });
      }
    }
  })
</script>
{% for post in posts %}
  {% include "includes/carousel-js.html" with images=post.images.all %}
{% endfor %}
{% endblock %}